-- =========================================================
-- PRESENCE STATUS ENUM
-- =========================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'presence_status'
      AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public.presence_status AS ENUM (
      'hadir',
      'sakit',
      'izin_terlambat',
      'cuti',
      'lapangan',
      'wfh',
      'off'
    );
  ELSE
    ALTER TYPE public.presence_status ADD VALUE IF NOT EXISTS 'off';
  END IF;
END
$$;


-- =========================================================
-- TEAM MEMBERS TABLE
-- =========================================================

CREATE TABLE IF NOT EXISTS public.team_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  role text NOT NULL,
  department text NOT NULL,
  avatar_url text,
  status public.presence_status NOT NULL DEFAULT 'hadir',
  status_note text,
  updated_at timestamptz NOT NULL DEFAULT now()
);


-- =========================================================
-- UPDATED_AT FUNCTION
-- =========================================================

CREATE OR REPLACE FUNCTION public.set_team_members_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


-- =========================================================
-- UPDATED_AT TRIGGER
-- =========================================================

DROP TRIGGER IF EXISTS team_members_updated_at
ON public.team_members;

CREATE TRIGGER team_members_updated_at
BEFORE UPDATE ON public.team_members
FOR EACH ROW
EXECUTE FUNCTION public.set_team_members_updated_at();


-- =========================================================
-- TEAM MEMBERS RLS
-- =========================================================

ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;


-- Remove existing policies first
DROP POLICY IF EXISTS "Public read team members"
ON public.team_members;

DROP POLICY IF EXISTS "Public insert team members"
ON public.team_members;

DROP POLICY IF EXISTS "Public update team members"
ON public.team_members;

DROP POLICY IF EXISTS "Public delete team members"
ON public.team_members;


-- Recreate policies
CREATE POLICY "Public read team members"
ON public.team_members
FOR SELECT
USING (true);

CREATE POLICY "Public insert team members"
ON public.team_members
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Public update team members"
ON public.team_members
FOR UPDATE
USING (true)
WITH CHECK (true);

CREATE POLICY "Public delete team members"
ON public.team_members
FOR DELETE
USING (true);


-- =========================================================
-- SUPABASE REALTIME
-- =========================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'team_members'
  ) THEN
    ALTER PUBLICATION supabase_realtime
    ADD TABLE public.team_members;
  END IF;
END
$$;


-- =========================================================
-- APP SETTINGS TABLE
-- =========================================================

CREATE TABLE IF NOT EXISTS public.app_settings (
  key text PRIMARY KEY,
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);


-- Default admin PIN and Auto-Schedule rules
INSERT INTO public.app_settings (key, value)
VALUES 
  ('admin_pin', '1234'),
  ('auto_schedule_rules', '[{"id":"1","time":"09:00","action":"restore_preset","weekdaysOnly":true,"enabled":true},{"id":"2","time":"18:00","action":"off","weekdaysOnly":true,"enabled":true}]')
ON CONFLICT (key) DO NOTHING;


-- =========================================================
-- APP SETTINGS RLS
-- =========================================================

ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;


-- Remove existing policies first
DROP POLICY IF EXISTS "Public read app settings"
ON public.app_settings;

DROP POLICY IF EXISTS "Public insert app settings"
ON public.app_settings;

DROP POLICY IF EXISTS "Public update app settings"
ON public.app_settings;


-- Recreate policies
CREATE POLICY "Public read app settings"
ON public.app_settings
FOR SELECT
USING (true);

CREATE POLICY "Public insert app settings"
ON public.app_settings
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Public update app settings"
ON public.app_settings
FOR UPDATE
USING (true)
WITH CHECK (true);


-- =========================================================
-- SERVER-SIDE AUTO-SCHEDULE
-- =========================================================

-- Change this value to the IANA timezone used by your office.
INSERT INTO public.app_settings (key, value)
VALUES ('schedule_timezone', 'Asia/Jakarta')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.schedule_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id text NOT NULL,
  rule_time text NOT NULL,
  scheduled_date date NOT NULL,
  action text NOT NULL,
  status text NOT NULL CHECK (status IN ('completed', 'failed')),
  error text,
  executed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (rule_id, rule_time, scheduled_date)
);

ALTER TABLE public.schedule_runs ENABLE ROW LEVEL SECURITY;

-- The scheduler is transactional: a failed snapshot or restore rolls back the
-- member changes and the run claim so the next cron tick can retry.
CREATE OR REPLACE FUNCTION public.run_auto_schedule()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rules jsonb;
  rule jsonb;
  office_timezone text;
  office_now timestamp;
  scheduled_minute timestamp;
  claimed_run_id bigint;
  preset jsonb;
  affected integer;
  completed integer := 0;
  action_name text;
BEGIN
  SELECT value
  INTO office_timezone
  FROM public.app_settings
  WHERE key = 'schedule_timezone';

  office_timezone := COALESCE(office_timezone, 'Asia/Jakarta');
  office_now := date_trunc('minute', now() AT TIME ZONE office_timezone);

  SELECT value::jsonb
  INTO rules
  FROM public.app_settings
  WHERE key = 'auto_schedule_rules';

  IF rules IS NULL OR jsonb_typeof(rules) <> 'array' THEN
    RETURN 0;
  END IF;

  FOR rule IN SELECT value FROM jsonb_array_elements(rules)
  LOOP
    IF COALESCE((rule->>'enabled')::boolean, true) = false
       OR rule->>'id' IS NULL
       OR rule->>'time' !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
       OR (COALESCE((rule->>'weekdaysOnly')::boolean, true)
           AND extract(isodow FROM office_now) > 5) THEN
      CONTINUE;
    END IF;

    scheduled_minute := date_trunc('day', office_now) + (rule->>'time')::time;
    IF scheduled_minute <> office_now THEN
      CONTINUE;
    END IF;

    action_name := COALESCE(rule->>'action', rule->>'status');
    IF action_name IS NULL THEN
      CONTINUE;
    END IF;

    INSERT INTO public.schedule_runs (
      rule_id, rule_time, scheduled_date, action, status
    ) VALUES (
      rule->>'id', rule->>'time', office_now::date, action_name, 'completed'
    )
    ON CONFLICT (rule_id, rule_time, scheduled_date) DO NOTHING
    RETURNING id INTO claimed_run_id;

    IF claimed_run_id IS NULL THEN
      CONTINUE;
    END IF;

    IF action_name = 'off' THEN
      SELECT jsonb_build_object(
        'savedAt', now(),
        'members', jsonb_agg(jsonb_build_object(
          'id', id,
          'status', status,
          'statusNote', status_note
        ))
      )
      INTO preset
      FROM public.team_members;

      IF preset->'members' IS NULL OR preset->'members' = 'null'::jsonb THEN
        RAISE EXCEPTION 'No members to save before off action';
      END IF;

      INSERT INTO public.app_settings (key, value, updated_at)
      VALUES ('saved_presence_preset', preset::text, now())
      ON CONFLICT (key) DO UPDATE
      SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at;

      UPDATE public.team_members SET status = 'off';
    ELSIF action_name = 'restore_preset' THEN
      SELECT value::jsonb
      INTO preset
      FROM public.app_settings
      WHERE key = 'saved_presence_preset';

      IF preset IS NULL OR jsonb_typeof(preset->'members') <> 'array' THEN
        RAISE EXCEPTION 'No valid saved preset found';
      END IF;

      UPDATE public.team_members AS member
      SET status = saved.status::public.presence_status,
          status_note = saved."statusNote"
      FROM jsonb_to_recordset(preset->'members')
        AS saved(id uuid, status text, "statusNote" text)
      WHERE member.id = saved.id;

      GET DIAGNOSTICS affected = ROW_COUNT;
      IF affected = 0 THEN
        RAISE EXCEPTION 'Saved preset did not match any members';
      END IF;
    ELSIF action_name IN ('hadir', 'sakit', 'izin_terlambat', 'cuti', 'lapangan', 'wfh') THEN
      UPDATE public.team_members
      SET status = action_name::public.presence_status;
    ELSE
      RAISE EXCEPTION 'Unsupported schedule action: %', action_name;
    END IF;

    completed := completed + 1;
    claimed_run_id := NULL;
  END LOOP;

  RETURN completed;
END;
$$;

REVOKE ALL ON FUNCTION public.run_auto_schedule() FROM PUBLIC, anon, authenticated;

-- Supabase Cron runs this function every minute. Re-running this schema replaces
-- the existing job instead of creating duplicates.
CREATE EXTENSION IF NOT EXISTS pg_cron;

DO $$
DECLARE
  existing_job_id bigint;
BEGIN
  SELECT jobid INTO existing_job_id
  FROM cron.job
  WHERE jobname = 'run-auto-schedule';

  IF existing_job_id IS NOT NULL THEN
    PERFORM cron.unschedule(existing_job_id);
  END IF;

  PERFORM cron.schedule(
    'run-auto-schedule',
    '* * * * *',
    'SELECT public.run_auto_schedule();'
  );
END
$$;
