import React, { useState } from 'react';
import { Check, Clock, Edit2, MessageSquare, Trash2 } from 'lucide-react';
import { PresenceStatus, STATUS_CONFIG, TeamMember } from '../types';

interface MemberCardProps { member: TeamMember; onUpdateStatus: (id: string, status: PresenceStatus, note?: string) => void; onEdit: (member: TeamMember) => void; onDelete: (id: string) => void; }

const timeAgo = (isoDate: string) => { const minutes = Math.max(0, Math.floor((Date.now() - new Date(isoDate).getTime()) / 60000)); if (minutes < 1) return 'Just now'; if (minutes < 60) return `${minutes}m ago`; const hours = Math.floor(minutes / 60); return hours < 24 ? `${hours}h ago` : `${Math.floor(hours / 24)}d ago`; };

export const MemberCard: React.FC<MemberCardProps> = ({ member, onUpdateStatus, onEdit, onDelete }) => {
  const [editingNote, setEditingNote] = useState(false);
  const [note, setNote] = useState(member.statusNote || '');
  const config = STATUS_CONFIG[member.status];
  const saveNote = () => { onUpdateStatus(member.id, member.status, note); setEditingNote(false); };
  const remove = () => { if (window.confirm(`Remove ${member.name} from the directory?`)) onDelete(member.id); };

  return <article className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-x-4 gap-y-3 border-b border-stone-200 px-5 py-5 last:border-b-0 sm:grid-cols-[minmax(0,1fr)_150px_110px]">
    <div className="min-w-0"><div className="flex items-center gap-3"><div className="relative shrink-0">{member.avatarUrl ? <img src={member.avatarUrl} alt="" className="h-11 w-11 rounded-full border border-stone-200 bg-stone-100 object-cover" onError={(event) => { event.currentTarget.style.display = 'none'; }} /> : <div className="grid h-11 w-11 place-items-center rounded-full bg-stone-200 font-serif text-lg text-stone-700">{member.name.charAt(0)}</div>}<span className={`absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-[#fbfaf7] ${config.dotClass}`} /></div><div className="min-w-0"><h3 className="truncate font-serif text-xl leading-tight text-stone-950">{member.name}</h3><p className="mt-0.5 truncate text-sm text-stone-500">{member.role} <span className="text-stone-300">/</span> {member.department}</p></div></div>{editingNote ? <div className="mt-3 flex gap-2"><input autoFocus value={note} onChange={(event) => setNote(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') saveNote(); if (event.key === 'Escape') setEditingNote(false); }} placeholder="Add availability context" className="min-w-0 flex-1 rounded-md border border-stone-300 bg-white px-3 py-2 text-sm outline-none focus:border-stone-900 focus:ring-2 focus:ring-stone-900/10" /><button onClick={saveNote} aria-label="Save note" className="grid h-9 w-9 place-items-center rounded-md bg-stone-900 text-white"><Check className="h-4 w-4" /></button></div> : <button onClick={() => { setNote(member.statusNote || ''); setEditingNote(true); }} className="mt-2 flex max-w-full items-center gap-1.5 text-left text-sm text-stone-500 transition hover:text-stone-950 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-stone-900"><MessageSquare className="h-3.5 w-3.5 shrink-0" /><span className="truncate">{member.statusNote || 'Add availability context'}</span></button>}</div>
    <div className="hidden sm:block"><label className="sr-only" htmlFor={`status-${member.id}`}>Update status for {member.name}</label><select id={`status-${member.id}`} value={member.status} onChange={(event) => onUpdateStatus(member.id, event.target.value as PresenceStatus)} className="w-full cursor-pointer rounded-md border border-stone-300 bg-white px-2 py-2 text-xs font-bold text-stone-700 outline-none focus:border-stone-900 focus:ring-2 focus:ring-stone-900/10">{(Object.keys(STATUS_CONFIG) as PresenceStatus[]).map((status) => <option key={status} value={status}>{STATUS_CONFIG[status].label}</option>)}</select></div>
    <div className="flex items-center justify-end gap-1.5"><span className="hidden items-center gap-1 font-mono text-[11px] text-stone-400 md:flex"><Clock className="h-3 w-3" />{timeAgo(member.updatedAt)}</span><button onClick={() => onEdit(member)} aria-label={`Edit ${member.name}`} className="grid h-9 w-9 place-items-center rounded-full text-stone-500 transition hover:bg-stone-200 hover:text-stone-950 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-stone-900"><Edit2 className="h-4 w-4" /></button><button onClick={remove} aria-label={`Remove ${member.name}`} className="grid h-9 w-9 place-items-center rounded-full text-stone-400 transition hover:bg-rose-50 hover:text-rose-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-stone-900"><Trash2 className="h-4 w-4" /></button></div>
  </article>;
};
